---
- name: add node repository
  sudo: true
  apt_repository: >
    repo='ppa:chris-lea/node.js'
    state=present
  tags:
    - node
    - repo

- name: install node
  sudo: true
  apt: >
    name=nodejs
    state=latest
  tags:
    - node
    - install
