---
- name: add precise repository
  sudo: true
  apt_repository: >
    repo='deb http://archive.ubuntu.com/ubuntu/ precise main universe'
    state=present
  tags:
    - system
    - repo

- name: enable gpg precise
  sudo: true
  apt_key: >
    id=40976EAF437D05B5
    keyserver=keyserver.ubuntu.com
    state=present
  tags:
    - system
    - repo

- name: install xml dependencies
  sudo: true
  apt: >
    name={{ item }}
    update_cache=yes
    state=present
  with_items:
    - libxml2=2.7.8.dfsg-5.1ubuntu4
    - libxml2-dev=2.7.8.dfsg-5.1ubuntu4
    - libxslt1.1=1.1.26-8ubuntu1
    - libxslt1-dev=1.1.26-8ubuntu1
    - libxmlsec1
    - libxmlsec1-dev
    - libxmlsec1-openssl
