---
- name: add postgres repository
  sudo: true
  apt_repository: >
    repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
    state=present
  tags:
    - database
    - repo


- name: enable postgres repository
  sudo: true
  apt_key: >
    url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state=present
  tags:
    - database
    - repo

